CREATE DATABASE SPACECOURSE_DB
CREATE TABLE NGUOIDUNG(
    USERNAME VARCHAR(50) PRIMARY KEY,
    EMAIL VARCHAR(100),
    PASSWD VARCHAR(100), 
    PROFILEPIC VARCHAR(1024) DEFAULT '~/Content/img/DefaultPFP.png',
    PREMIUM INT DEFAULT 0, --0: free, 1: tháng, 2: năm, 3: forever
)
CREATE TABLE THANHTOAN(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    USERNAME VARCHAR(50) CONSTRAINT FK_TT FOREIGN KEY REFERENCES NGUOIDUNG(USERNAME),
    LOAITHE INT,
    SOTHE VARCHAR(16),
    CVC CHAR(3) NULL,
    EXPIRE DATE NULL,
)
CREATE TABLE KHOAHOC(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NGUOIHOC VARCHAR(50) CONSTRAINT FK_KH FOREIGN KEY REFERENCES NGUOIDUNG(USERNAME),
    COURSE_NAME NVARCHAR(256),
    COURSE_DESC NVARCHAR(2048),
    IMG_SRC VARCHAR(1024),
    ACCENT_COLOR CHAR(7),
)
CREATE TABLE BAIHOC(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    KHAHOC INT CONSTRAINT FK_BH REFERENCES KHOAHOC(ID),
    VID_NAME NVARCHAR(256),
    VID_DESC NVARCHAR(2048),
    VID_SRC VARCHAR(1024),
    LUOTXEM INT,
)
CREATE TABLE COMMENT(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NGUOIDANG VARCHAR(50) CONSTRAINT FK_ND REFERENCES NGUOIDUNG(USERNAME),
    VIDEO INT CONSTRAINT FK_CMT REFERENCES BAIHOC(ID),
    NOIDUNG NVARCHAR(1024),
)
CREATE TABLE FORUM(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NGUOIDANG VARCHAR(50) CONSTRAINT FK_FR REFERENCES NGUOIDUNG(USERNAME),
    KHOAHOC INT CONSTRAINT FK_FR_T REFERENCES KHOAHOC(ID),
    POST_TITLE NVARCHAR(256) NULL,
    POST_CONTENT NVARCHAR(2048),
)
CREATE TABLE FORUM_REPLY(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NGUOIDANG VARCHAR(50) CONSTRAINT FK_FRE REFERENCES NGUOIDUNG(USERNAME),
    TOPIC INT CONSTRAINT FK_FRE_TP REFERENCES FORUM(ID),
    POST_TITLE NVARCHAR(256) NULL,
    POST_CONTENT NVARCHAR(2048),
)