//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAIHOC
    {
        public BAIHOC()
        {
            this.COMMENTs = new HashSet<COMMENT>();
        }
    
        public int ID { get; set; }
        public Nullable<int> KHAHOC { get; set; }
        public string VID_NAME { get; set; }
        public string VID_DESC { get; set; }
        public string VID_SRC { get; set; }
        public Nullable<int> LUOTXEM { get; set; }
    
        public virtual KHOAHOC KHOAHOC { get; set; }
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
    }
}
