//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAIHOC
    {
        public BAIHOC()
        {
            this.KHOAHOCs = new HashSet<KHOAHOC>();
        }
    
        public int ID { get; set; }
        public string NGUOIDANG { get; set; }
        public string TITLE { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> LUOTXEM { get; set; }
        public string NGUOIHOC { get; set; }
        public Nullable<int> TIENTRINH { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG1 { get; set; }
        public virtual ICollection<KHOAHOC> KHOAHOCs { get; set; }
    }
}
