//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENT
    {
        public int ID { get; set; }
        public string NGUOIDANG { get; set; }
        public Nullable<int> VIDEO { get; set; }
        public string NOIDUNG { get; set; }
    
        public virtual BAIHOC BAIHOC { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
