//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public Courses()
        {
            this.Feedback = new HashSet<Feedback>();
            this.Lessons = new HashSet<Lessons>();
        }
    
        public int id_course { get; set; }
        public Nullable<int> subscriber_user { get; set; }
        public byte[] is_premium { get; set; }
        public Nullable<double> process { get; set; }
        public string name_course { get; set; }
        public string description { get; set; }
        public string img_course { get; set; }
        public string accent_color { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Feedback> Feedback { get; set; }
        public virtual ICollection<Lessons> Lessons { get; set; }
    }
}
