//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.Followers = new HashSet<Follower>();
            this.Lessons = new HashSet<Lesson>();
        }
    
        public int id_course { get; set; }
        public Nullable<int> subscriber_user { get; set; }
        public byte[] is_premium { get; set; }
        public Nullable<double> process { get; set; }
        public string name_course { get; set; }
        public string description { get; set; }
        public string img_course { get; set; }
        public string accent_color { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<Follower> Followers { get; set; }
        public virtual ICollection<Lesson> Lessons { get; set; }
    }
}
