//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORUM
    {
        public FORUM()
        {
            this.FORUM_REPLY = new HashSet<FORUM_REPLY>();
        }
    
        public int ID { get; set; }
        public string NGUOIDANG { get; set; }
        public Nullable<int> KHOAHOC { get; set; }
        public string POST_TITLE { get; set; }
        public string POST_CONTENT { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual KHOAHOC KHOAHOC1 { get; set; }
        public virtual ICollection<FORUM_REPLY> FORUM_REPLY { get; set; }
    }
}
