//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lessons
    {
        public Lessons()
        {
            this.Cerf = new HashSet<Cerf>();
        }
    
        public int id_lesson { get; set; }
        public Nullable<double> process { get; set; }
        public Nullable<int> id_user { get; set; }
        public string name_lesson { get; set; }
        public string description { get; set; }
        public string video_lesson { get; set; }
        public Nullable<int> id_course { get; set; }
    
        public virtual ICollection<Cerf> Cerf { get; set; }
        public virtual Courses Courses { get; set; }
        public virtual Users Users { get; set; }
    }
}
