//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceCourse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SPACECOURSE_DB : DbContext
    {
        public SPACECOURSE_DB()
            : base("name=SPACECOURSE_DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BAIHOC> BAIHOCs { get; set; }
        public DbSet<COMMENT> COMMENTs { get; set; }
        public DbSet<FORUM> Fora { get; set; }
        public DbSet<FORUM_REPLY> FORUM_REPLY { get; set; }
        public DbSet<KHOAHOC> KHOAHOCs { get; set; }
        public DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public DbSet<THANHTOAN> THANHTOANs { get; set; }
    }
}
