//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        public NGUOIDUNG()
        {
            this.BAIHOCs = new HashSet<BAIHOC>();
            this.BAIHOCs1 = new HashSet<BAIHOC>();
            this.KHOAHOCs = new HashSet<KHOAHOC>();
            this.THANHTOANs = new HashSet<THANHTOAN>();
        }
    
        public string USERNAME { get; set; }
        public string HOTEN { get; set; }
        public string PASSWORD_HASH { get; set; }
        public System.DateTime NGAYSINH { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public int CHUCVU { get; set; }
    
        public virtual ICollection<BAIHOC> BAIHOCs { get; set; }
        public virtual ICollection<BAIHOC> BAIHOCs1 { get; set; }
        public virtual ICollection<KHOAHOC> KHOAHOCs { get; set; }
        public virtual ICollection<THANHTOAN> THANHTOANs { get; set; }
    }
}
