//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceCourse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    public partial class NGUOIDUNG
    {
        public NGUOIDUNG()
        {
            this.COMMENTs = new HashSet<COMMENT>();
            this.Fora = new HashSet<FORUM>();
            this.FORUM_REPLY = new HashSet<FORUM_REPLY>();
            this.KHOAHOCs = new HashSet<KHOAHOC>();
            this.THANHTOANs = new HashSet<THANHTOAN>();
            PROFILEPIC = "~/Content/img/DefaultPFP.png";
            PREMIUM = 0;
        }
        public string USERNAME { get; set; }
        public string EMAIL { get; set; }
        public string PASSWD { get; set; }
        public string PROFILEPIC { get; set; }
        public Nullable<int> PREMIUM { get; set; }
    
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
        public virtual ICollection<FORUM> Fora { get; set; }
        public virtual ICollection<FORUM_REPLY> FORUM_REPLY { get; set; }
        public virtual ICollection<KHOAHOC> KHOAHOCs { get; set; }
        public virtual ICollection<THANHTOAN> THANHTOANs { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }
    }
}
