//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        public int id { get; set; }
        public string loaithe { get; set; }
        public Nullable<System.DateTime> ngaythanhtoan { get; set; }
        public Nullable<int> cvc { get; set; }
        public Nullable<System.DateTime> expire { get; set; }
        public Nullable<int> sothe { get; set; }
        public Nullable<int> madv { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
