//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int id_service { get; set; }
        public Nullable<System.DateTime> date_regis { get; set; }
        public string type_service { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual User User { get; set; }
    }
}
