//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceCourse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SPACECOURSE_DBEntities1 : DbContext
    {
        public SPACECOURSE_DBEntities1()
            : base("name=SPACECOURSE_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cerf> Cerf { get; set; }
        public DbSet<Courses> Courses { get; set; }
        public DbSet<Feedback> Feedback { get; set; }
        public DbSet<Lessons> Lessons { get; set; }
        public DbSet<Pay> Pay { get; set; }
        public DbSet<Services> Services { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<AdminUser> AdminUser { get; set; }
    }
}
