//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOAN
    {
        public string USERNAMEOWNER { get; set; }
        public string SOTHE { get; set; }
        public Nullable<int> LOAITHE { get; set; }
        public string CVV { get; set; }
        public Nullable<System.DateTime> EXPIRE { get; set; }
        public string CHUTHE { get; set; }
        public int ID_THANHTOAN { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
