//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceCourse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Text;

    public partial class User
    {
        public User()
        {
            this.Certificates = new HashSet<Certificate>();
            this.Courses = new HashSet<Cours>();
            this.Feedbacks = new HashSet<Feedback>();
            this.Lessons = new HashSet<Lesson>();
            this.Pays = new HashSet<Pay>();
            this.Services = new HashSet<Service>();
            profile_pic = "~/Content/img/Light_logo.png";
        }
        public int id_user { get; set; }
        public string name_user { get; set; }
        [Required(ErrorMessage = "Mật khẩu không được rỗng!")]
        [RegularExpression("(?!^[0-9]*$)(?!^[a-zA-Z]*$)^([a-zA-Z0-9]{8,10})$", ErrorMessage = "Mật khẩu không hợp lệ!")]
        public string user_password { get; set; }
        public string sdt { get; set; }
        [Required(ErrorMessage = "Email không được rỗng!")]
        [RegularExpression("^(?(\"\")(\\\"\\\".+?\"\"@)|(([0-9a-zA-Z]((\\.(?!\\.))|[-!#\\$%&'\\*\\+/=\\?\\^`\\{\\}\\|~\\w])*)(?<=[0-9a-zA-Z])@))(?(\\[)(\\[(\\d{1,3}\\.){3}\\d{1,3}\\])|(([0-9a-zA-Z][-\\w]*[0-9a-zA-Z]\\.)+[a-zA-Z]{2,6}))$", ErrorMessage = "Email không hợp lệ!")]
        public string emai { get; set; }
        [Required(ErrorMessage = "Username không được rỗng!")]
        [MinLength(4, ErrorMessage = "Username quá ngắn.")]
        [MaxLength(20, ErrorMessage = "Username quá dài.")]
        [RegularExpression("^[a-zA-Z0-9!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/?]*$", ErrorMessage = "Username chứa ký tự đặc biệt.")]
        public string user_name { get; set; }
        public string profile_pic { get; set; }
        public virtual ICollection<Certificate> Certificates { get; set; }
        public virtual ICollection<Cours> Courses { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<Lesson> Lessons { get; set; }
        public virtual ICollection<Pay> Pays { get; set; }
        public virtual ICollection<Service> Services { get; set; }
        public virtual AdminUser AdminUser { get; set; }
        [NotMapped]
        [Compare("user_password", ErrorMessage = "M?t kh?u không kh?p.")]
        public string re_password { get; set; }
        [Required(ErrorMessage = "Vui lòng ch?p nh?n ?i?u kho?n.")]
        public bool accept_eula { get; set; }
    }
}
