//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Cerf = new HashSet<Cerf>();
            this.Courses = new HashSet<Courses>();
            this.Feedback = new HashSet<Feedback>();
            this.Lessons = new HashSet<Lessons>();
            this.Pay = new HashSet<Pay>();
            this.Services = new HashSet<Services>();
        }
    
        public int id_user { get; set; }
        public string name_user { get; set; }
        public string user_password { get; set; }
        public string sdt { get; set; }
        public string emai { get; set; }
        public string user_name { get; set; }
        public string profile_pic { get; set; }
        public string re_password { get; set; }
    
        public virtual ICollection<Cerf> Cerf { get; set; }
        public virtual ICollection<Courses> Courses { get; set; }
        public virtual ICollection<Feedback> Feedback { get; set; }
        public virtual ICollection<Lessons> Lessons { get; set; }
        public virtual ICollection<Pay> Pay { get; set; }
        public virtual ICollection<Services> Services { get; set; }
        public virtual AdminUser AdminUser { get; set; }
    }
}
