//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Cerfs = new HashSet<Cerf>();
            this.Courses = new HashSet<Cours>();
            this.Feedbacks = new HashSet<Feedback>();
            this.Lessons = new HashSet<Lesson>();
            this.Pays = new HashSet<Pay>();
            this.Services = new HashSet<Service>();
        }
    
        public int id_user { get; set; }
        public string name_user { get; set; }
        public string user_password { get; set; }
        public string sdt { get; set; }
        public string emai { get; set; }
        public string user_name { get; set; }
        public string profile_pic { get; set; }
    
        public virtual ICollection<Cerf> Cerfs { get; set; }
        public virtual ICollection<Cours> Courses { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<Lesson> Lessons { get; set; }
        public virtual ICollection<Pay> Pays { get; set; }
        public virtual ICollection<Service> Services { get; set; }
        public virtual AdminUser AdminUser { get; set; }
    }
}
